In [3]:
import numpy as np
import matplotlib.pyplot as plt

# Задача 1

In [29]:
A = np.array([
    [-34,64, 56, 75],
    [26, -2, -16, -102],
    [-47, -124, -44, 18]
])

In [30]:
AAT = A @ A.T
AAT

array([[14013, -9558, -7452],
       [-9558, 11340, -2106],
       [-7452, -2106, 19845]])

In [49]:
eig, U = np.linalg.eig(AAT)
idx = np.argsort(eig,)[::-1]
eig = eig[idx]
U = U[:,idx]
np.sqrt(eig), U

(array([162., 135.,  27.]),
 array([[ 0.66666667,  0.33333333,  0.66666667],
        [-0.33333333, -0.66666667,  0.66666667],
        [-0.66666667,  0.66666667,  0.33333333]]))

In [41]:
Vt = np.diag(1/np.sqrt(eig)) @ U.T @ A
Vt

array([[-1.69135539e-16,  7.77777778e-01,  4.44444444e-01,
         4.44444444e-01],
       [-4.44444444e-01, -4.44444444e-01,  3.46944695e-18,
         7.77777778e-01],
       [-7.77777778e-01, -1.30451205e-15,  4.44444444e-01,
        -4.44444444e-01]])

In [42]:
U @ np.diag(np.sqrt(eig)) @ Vt

array([[ -34.,   64.,   56.,   75.],
       [  26.,   -2.,  -16., -102.],
       [ -47., -124.,  -44.,   18.]])

In [45]:
A_1 = U[:,:2] @ np.diag(np.sqrt(eig))[:2,:2] @ Vt[:2,:]
A_1

array([[ -20.,   64.,   48.,   83.],
       [  40.,   -2.,  -24.,  -94.],
       [ -40., -124.,  -48.,   22.]])

In [48]:
Ur, Sr, Vr = np.linalg.svd(A - A_1)
Sr

array([2.70000000e+01, 9.12694660e-14, 7.68463443e-14])

# Задача 2

In [50]:
A = np.array([
    [4.01, -0.16],[5.9, -6.01]
])
b = np.array([3.81, 0.02])

In [64]:
Ah = A.round()
Ah

array([[ 4., -0.],
       [ 6., -6.]])

In [65]:
Ar = np.linalg.inv(Ah)
Ar

array([[ 2.50000000e-01,  9.25185854e-18],
       [ 2.50000000e-01, -1.66666667e-01]])

In [74]:
np.sqrt(np.linalg.eig(Ah.T @ Ah)[0].max()) * np.sqrt(np.linalg.eig(Ar.T @ Ar)[0].max())

3.3699240762154807

In [75]:
dA = Ah - A
dA

array([[-0.01,  0.16],
       [ 0.1 ,  0.01]])

In [77]:
abs(dA).sum(axis=0)

array([0.11, 0.17])

In [81]:
np.sqrt(np.linalg.eig(A.T @ A)[0].max())

8.96457248821069

In [80]:
0.17/11.91

0.014273719563392108

In [89]:
0.21/3.83

0.054830287206266315

In [79]:
np.sqrt(np.linalg.eig(dA.T @ dA)[0].max()) / 8.99

0.0178402723141327

In [87]:
v = np.array([3.81,0.02])
np.linalg.norm(v,2)

3.8100524930767032

# Задача 4

In [97]:
A = np.array([
    [5,8],
    [9,6]
])
A

array([[5, 8],
       [9, 6]])

In [98]:
np.linalg.inv(A) * 42

array([[-6.,  8.],
       [ 9., -5.]])

In [99]:
0.02*15/42 / (1 - 0.02*15/42)

0.007194244604316546

# Задача 3

In [172]:
A = np.array([
    [-16,-8],
    [-2,-4]
])
b=np.array([1,-4])

In [173]:
np.linalg.solve(A,b) * 8

array([-6., 11.])

In [174]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.08333333,  0.16666667],
       [ 0.04166667, -0.33333333]])

In [175]:
np.sqrt(np.linalg.eig(A.T @ A)[0].max())

18.250556184817203

In [157]:
18.250556184817203 * 0.3802199205170251

6.939225021982697

In [176]:
np.sqrt(np.linalg.eig(A_inv.T @ A_inv)[0].max())

0.3802199205170251

In [158]:
dA = np.array([
    [0.2, 0.2],
    [0,0.2]
])
np.sqrt(np.linalg.eig(dA.T @ dA)[0].max())

0.323606797749979

In [178]:
0.323606797749979 / 18.250556184817203

0.01773133895060088

In [177]:
0.4 /  24

0.016666666666666666

In [165]:
0.05 * np.sqrt(2) / np.sqrt(17)

0.017149858514250885

In [162]:
0.05 / 4

0.0125

In [181]:
(0.018 + 0.0171) / (1 - 0.018 * 6.94) * 6.94

0.2783676920967226

In [182]:
(0.017 + 0.0125) / (1 - 0.017 * 9) * 9

0.3134592680047226

# Задача 5

In [20]:
A = np.array([
    [25,5,7],
    [4,24,6],
    [4,1,24]
])
b = np.array([8,1,7])

D = np.diag(A)
revD = np.diag(1/D)
Bmat = revD @ (np.diag(D) - A)
bnew = b / D
Bmat, bnew

(array([[ 0.        , -0.2       , -0.28      ],
        [-0.16666667,  0.        , -0.25      ],
        [-0.16666667, -0.04166667,  0.        ]]),
 array([0.32      , 0.04166667, 0.29166667]))

In [24]:
x0 = np.array([0,0,0])
x = x0.copy()
first = True
i = 0
while not np.allclose(x,x0, atol=1e-2) or first:
    first=False
    x0 = x.copy()
    i += 1
    x = Bmat @ x0 + bnew
print(x, i)

[ 0.26384525 -0.0637607   0.25127863] 5


In [25]:
np.linalg.solve(A,b)

array([ 0.26279632, -0.06477427,  0.25056621])

# Задача 6

In [130]:
A = np.array([
    [1,0,1,1,1],
    [0,1,0,1,1],
    [0,0,1,0,1],
    [0,0,1,0,0],
    [0,1,0,0,0]
])
A = np.array([
    [1, 1, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 1, 1, 1, 0],
    [0, 1, 0, 1, 1]
])
alpha = 0.85
beta = 1. - alpha
P = A / A.sum(axis=0)
P

array([[0.33333333, 0.33333333, 0.        , 0.        , 0.        ],
       [0.33333333, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.33333333, 0.5       , 0.5       , 0.        ],
       [0.        , 0.33333333, 0.        , 0.5       , 0.5       ]])

In [131]:
x_rand = np.ones(5) / 5
x0 = x_rand.copy()
x = x0.copy()
for i in range(200):
    x = alpha * P @ x0 + beta * x_rand
    x0 = x.copy()
print(x / alpha)

[0.07117365 0.05545998 0.32635133 0.36499646 0.35848917]


In [183]:
# Задача 7

In [192]:
A = np.array([
    [0, -7, 8],
    [-1,9,-7],
    [-1,5,-3]
])
x = A + np.eye(3) * 3
s = np.zeros(x.shape)
i = 1
x_n = np.eye(3)
for i in range(1,20):
    x_n = x_n @ x
    t0 = (-1) ** (i+1) * x_n / i
    s += t0
    i += 1
    if np.allclose(t0, np.zeros(t0.shape), atol=1e-5):
        break
print(s)

[[-4.35274546e+10 -5.21564488e+14  5.21619464e+14]
 [-5.49755814e+10  2.08516989e+15 -2.08510347e+15]
 [-5.49755814e+10  1.56381386e+15 -1.56374743e+15]]


In [193]:
np.linalg.eig(A)

EigResult(eigenvalues=array([1.+6.06273063e-08j, 1.-6.06273063e-08j, 4.+0.00000000e+00j]), eigenvectors=array([[ 0.57735027+0.00000000e+00j,  0.57735027-0.00000000e+00j,
         0.19611614+0.00000000e+00j],
       [ 0.57735027+3.50031916e-08j,  0.57735027-3.50031916e-08j,
        -0.78446454+0.00000000e+00j],
       [ 0.57735027+3.50031916e-08j,  0.57735027-3.50031916e-08j,
        -0.58834841+0.00000000e+00j]]))